espressif/github-actions

.github/main.workflow, .github/workflows/test_jira_sync.yml, sync_issues_to_jira/Dockerfile, sync_issues_to_jira/sync_issue.py, sync_issues_to_jira/sync_pr.py, sync_issues_to_jira/sync_to_jira.py, sync_issues_to_jira/test_sync_to_jira.py
=> adopt to new action scheme

sync_issues_to_jira/sync_pr.py, sync_issues_to_jira/sync_to_jira.py
This PR is trying to avoid syncing GitHub events to Jira if the issue owner is our collaborator.
=> donot sync issues from collaborators

sync_issues_to_jira/sync_to_jira.py
Allows collaborators to use 'Reference comment in new issue' and similar.
Includes second commit with infrastructure fixes: update the Docker image to Debian 10, fix an issue with the mocked objects in testing, pin all the package versions we use.
=> sync_to_jira: Only skip PRs opened by collaborators, not issues

README.md, release_zips/Dockerfile, release_zips/README.md, release_zips/release_zips.py
Automate creating and attaching recursive git clones of the repo to releases, such as the zip files we attach for ESP-IDF releases.
See README in the PR branch for details.
This private repo used for testing has some releases, example: https://github.com/espressif/actions-internal-test/releases/v1.0 (includes ESP-IDF in the zip file, Action took ~7 minutes to run.)
=> Add release_zips action

sync_issues_to_jira/sync_issue.py, sync_issues_to_jira/sync_to_jira.py
If a GitHub issue is opened and edited immediately (or labelled, etc) then there is a race between two GitHub Actions. The 'opened' event will always create a new JIRA issue, but in some cases edited/labelled events may need to create one as well (if the GitHub issue existed before syncing was enabled, or if there was some error creating the original JIRA ticket.)
Due each Action running independently, it's possible for the events to be processed out of order.
To work around the race, we wait for a while before creating any JIRA ticket in response to an edit event. This timeout may not have been enough, so extended now to a random timeout in the range 2.5-5 minutes.
It's still possible that some sequences of events will still result in duplicate JIRA tickets, though.
=> sync_issues_to_jira: Reduce duplicate JIRA issues

.github/workflows/lint.yml, README.md, upload_components/Dockerfile, upload_components/README.md, upload_components/action.yml, upload_components/upload.sh
Add configurable GitHub action to upload components from GitHub repo to [Espressif Component Service](https://components.espressif.com)
| Input            | Optional | Default   | Description                                                          |
| ---------------- | -------- | --------- | -------------------------------------------------------------------- |
| api_token        | ❌       |           | API Token for component service                                      |
| namespace        | ❌       |           | Component namespace                                                  |
| name             | ✔ / ❌   |           | Name of the component, required if only 1 directory is set           |
| directories      | ✔        | Repo root | Semicolon separated list of directories with …
=> Add github action to upload components

sync_issues_to_jira/README.md, sync_issues_to_jira/action.yml
The "Sync remain PRs to Jira" workflow in [esptool](https://github.com/espressif/esptool/blob/master/.github/workflows/new_prs.yml) and [esp-idf](https://github.com/espressif/esp-idf/blob/master/.github/workflows/new_prs.yml) is defined with the following non-existent input:
```
with:
cron_job: true
```
This results in a warning ([See this run](https://github.com/espressif/esptool/actions/runs/859825998)): `Unexpected input(s) 'cron_job', valid inputs are ['entryPoint', 'args']`
This PR adds a [metadata file](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) to the sync_issues_to_jira action and defines the `cron_job` input. This should solve the warnings in the esptool and esp_idf projects.
=> sync_issues_to_jira: Add action metadata file

sync_issues_to_jira/sync_issue.py
The [script fails](https://github.com/espressif/esp-idf/runs/3363129210?check_suite_focus=true#step:4:272) when no issue description is provided (trying to write a NoneType into a file).
---
Closes IDF-3740
=> bugfix: sync_issue: Allow parsing of empty markdown files

github_pr_to_internal_pr/README.md, github_pr_to_internal_pr/github_pr_to_internal_pr.py
- GitHub Actions clones the repository on which the workflow is need to be run, hence there is no need to clone the repository again
- Removed `time(sleep)` ([Ref](https://github.com/espressif/github-actions/pull/17#discussion_r703455914)) used for waiting to register remote branch (issue has been fixed on GitLab)
=> sync_approved_pr: Removed redundant `git clone` step

README.md, upload_components/README.md
Add deprecation notice to the readme, but keep the action in this repo.
**NB** This PR should be merged after https://github.com/espressif/upload-components-ci-action/pull/1
=> Add `upload_components` deprecation notice to the Readme

sync_issues_to_jira/sync_issue.py
Right now script tries to create new issue in Jira with type specified in label "Type: %s".
This works for Bug type, because we have GitHub label "Type: Bug" and also Bug issue type in Jira.
Unfortunately, the same can't be said about "Type: Feature Request" GitHub label, because there is no "Feature Request" issue type in Jira and such issues are created in Jira with default "Task" issue type. They should be created as "New Feature" instead and this PR fixes that.
=> Fix mapping of Type: Feature Request to New Feature issue type in Jira

github_pr_to_internal_pr/Dockerfile
- Fixed the `fatal: detected dubious ownership in repository at '/github/workspace'` issue
- https://github.com/actions/runner/issues/2033
- https://github.com/actions/checkout/issues/1048
- https://github.com/actions/runner-images/issues/6775
=> sync_approved_pr: Fix `dubious ownership in repository` issue

sync_issues_to_jira/sync_issue.py
Added one if into `_find_jira_issue` funnction that is called after issue is created. It checks if label on issue is "Type: Bug :bug:" and if so, returns Bug Jira issue type.
Also added variable JIRA_BUG_TYPE_ID variable holding ID of Bug type that gets returned.
=> Match label "Type: Bug 🐛" to Bug issue type in Jira

github_pr_to_internal_pr/Dockerfile
- Fixed the `fatal: detected dubious ownership in the repository at '/github/workspace'` issue
- Updates the non working fix merged in #35
- https://github.com/actions/runner/issues/2033
- https://github.com/actions/checkout/issues/1048
- https://github.com/actions/runner-images/issues/6775
=> sync_approved_pr: Add git repo to safe dir list

sync_issues_to_jira/README.md, sync_issues_to_jira/sync_issue.py, sync_issues_to_jira/sync_to_jira.py
This pull request adds option of manually mirroring of GH issues to Jira. If GH event name is `workflow_dispatch` and has attribute `action` set to `mirror issues, `sync_to_jira.py script will call `sync_issues_manually` function from `sync_issue.py` that will run on issues with numbers specified in `issue-numbers` when triggering workflow. Works both for issues and pull requests.
=> Add option to manually trigger mirroring of GH issues to Jira

sync_issues_to_jira/README.md, sync_issues_to_jira/sync_issue.py
When a user creates an issue and sets a label, Github generates two events: issue created, issue labeled.
Previously, before we started using `concurrency: jira_issues` in workflows, two workflows would be dispatched at the same time.
In this scenario, we wanted the "issue created" workflow to actually create the issue, and "issue labeled" workflow to only update it. This was achieved using the "retry and wait" logic in _find_jira_issue function. The workflow which handled "issue created" event would proceed to create an issue right away, while the workflow for "issue updated/labelled" would wait a random amount of time. Most of the time, this was sufficient to prevent duplicate issues from being created.
Once we have started using `concurrency: jira_issues`, all workflow runs related to …
=> sync_issues_to_jira: check for an existing issue when creating

github_pr_to_internal_pr/github_pr_to_internal_pr.py
The `github_pr_to_internal_pr.py` script doesn't set the `remove_source_branch` option when creating the Gitlab MR. Developers often forget to set that option manually as well when reviewing the automatically created MR. Thus, when the MR is merged, we often get a lot of stale branches that still exist.
=> Add 'remove_source_branch' option when creating an MR from a Github PR

sync_issues_to_jira/sync_issue.py
Modified mirroring script to set GitHub issue custom field to 'Open' when new issue is created or old one reopened and to 'Closed' when GitHub issue is closed.
=> Set GitHub issue custom field in jira

github_pr_to_internal_pr/github_pr_to_internal_pr.py
Automatic PR to internal MR creation workflow does not assign the MR to anyone. After this change, there will be a notification to the maintainers about the MR creation.
=> Notify IDF maintainers on the internal MR creation

update_submodule_versions/Dockerfile, update_submodule_versions/README.md, update_submodule_versions/action.yml, update_submodule_versions/entrypoint.sh, update_submodule_versions/requirements.txt, update_submodule_versions/test_update_submodule_versions.py, update_submodule_versions/update_submodule_versions.py
This action helps automate updates to repository submodules.
When the action is run, it will:
1. Read information about the submodules from .gitmodules file
2. For each submodule:
1. Check if there are new release tags in upstream repository
2. If yes, create a branch where the update will be performed
3. Update the submodule commit
4. Optionally, update idf_component.yml file with the new version
5. Push the branch to Github repository
6. Open a pull request
See https://github.com/espressif/idf-extra-components/pull/174 for the case where this action is applied and links for example PRs created using this action.
=> update_submodule_versions: add new action

danger_pr_review/README.md
This PR fixes an issue where `github-actions-bot` is unable to submit DangerJS output as a comment to a PR when the PR is created from an external contributor's fork.
- `on: pull_request_target` - GH actions are triggered without manual approval from repo maintainers for external contributors.
- `with: ref: ${{{ github.event.pull_request.head.sha }}` indicating the context in which the comment should be posted
- in the repo https://github.com/espressif/test-project-bot/pull/5
- [RDT-531](https://jira.espressif.com:8443/browse/RDT-531)
**Note:** This is just change of docs guide. The changes of the workflow have to be done in projects by PRs.
=> docs: Update sample workflow (usage DangerJS GH action)

danger_pr_review/dangerjs/dangerfile.ts, danger_pr_review/dangerjs/package-lock.json, danger_pr_review/dangerjs/package.json, danger_pr_review/dangerjs/prTargetBranch.ts
DangerJS check for `TARGET BRANCH` has currently hardcoded the default project branch name `master`/`main`.
If a contributor tries to target their PR to a branch with a different name, the Danger check fails.
In some projects, the default branch may be something different than `master`/`main`.
This change always retrieves the project's default branch from the GitHub API and compares it to the target PR branch.
- issue spotted in: https://github.com/espressif/idf-examples-launchpad-ci-action/pull/1#issuecomment-1696783378
=> change(dangerjs): Read default branch with GitHub API

sync_issues_to_jira/README.md, sync_issues_to_jira/sync_to_jira.py
This PR adds support for reading a token from the `JIRA_PASS` variable. This is here due to handle migration process from using username+password to PAT.
- If the `JIRA_PASS` variable starts with the `token:` prefix, token-based authentication will be used (strip `token:` part first).
- If the `JIRA_PASS` variable does not start with a `token:` prefix, basic authentication (username + password) will be used
The example workflows in the README documents retained the current version containing `JIRA_USER`. I recommend to keep it also in the template for new projects. It will be ignored anyway, but since there are already so many projects with it, maybe we can keep it as legacy code.
1) After merging this PR, set on org level:
- `JIRA_USER` (will be ignored during token authentication, but …
=> change(jira-auth): change JIRA auth method to use PAT

danger_pr_review/README.md, danger_pr_review/dangerjs/dangerfile.ts
This is adding deprecation warning to projects using old version of GitHub Danger linter.
- warning in docs
- warning in each output message so that project administrators can notice it
- *merge after:* https://github.com/espressif/shared-github-dangerjs/pull/1
=> change(danger-github): add deprecated warning message to action output

github_pr_to_internal_pr/github_pr_to_internal_pr.py
When syncing a Github PR to a Gitlab PR via the `PR-Sync-Rebase`, the sync script will automatically append a `Merges` line to the commit message. This extra line is misformatted, for example:
```
Some PR commit message
This commit updates ...
Mergeshttps://github.com/espressif/esp-idf/pull/XXXX
```
The `Closes` keyword [should be used instead](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link commit messages to PRs/Issues. For example...
```
Some PR commit message
This commit updates ...
Closes https://github.com/espressif/esp-idf/pull/XXXX
```
=>  fix(github_pr): "Closes" line formatting

sync_issues_to_jira/README.md, sync_issues_to_jira/action.yml, sync_issues_to_jira/sync_to_jira.py
This is to add deprecation information and warnings for JIRA sync actions with GitHub.
JIRA sync GitHub actions has been migrated to independent repo: https://github.com/espressif/sync-jira-actions
- https://github.com/espressif/test-project-bot/actions/runs/7898629371/job/21556407300#step:4:12
- https://github.com/espressif/sync-jira-actions/pull/1
=> change(jira-sync-actions): add deprecation info and warning message

github_pr_to_internal_pr/README.md, github_pr_to_internal_pr/action.yml, github_pr_to_internal_pr/github_pr_to_internal_pr.py
This is to add deprecation information and warnings for **Sync approved PRs to internal codebase**.
Sync approved PRs to internal codebase has been migrated to independent repo: https://github.com/espressif/sync-pr-to-gitlab
- https://github.com/espressif/sync-pr-to-gitlab/pull/1
=> change(github-pr-to-internal-pr): add deprecation info and warning message
